name: E2E test
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  # This workflow contains a single job called "build"
  test:
    if: github.event.pull_request.draft == false
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      # Runs a single command using the runners shell
      - name: Run Test
        run: echo Hello, world!
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Tests
        run: yarn test
