name: E2E test
on:
  pull_request_target:
    branches:
      - master

jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: microsoft/playwright-github-action@v1

      # Runs a single command using the runners shell
      - name: Run Test
        run: echo Hello, world!

      - name: Install deps
        run: yarn

      - name: Run Tests
        run: yarn test
